// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/images.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All     bool             `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`        // 是否全部
	Filters []*MapFieldEntry `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"` // filter
}

func (x *ImageListRequest) Reset() {
	*x = ImageListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListRequest) ProtoMessage() {}

func (x *ImageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListRequest.ProtoReflect.Descriptor instead.
func (*ImageListRequest) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{0}
}

func (x *ImageListRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ImageListRequest) GetFilters() []*MapFieldEntry {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ImageListEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Containers  int64            `protobuf:"varint,1,opt,name=Containers,proto3" json:"Containers,omitempty"`
	Created     int64            `protobuf:"varint,2,opt,name=Created,proto3" json:"Created,omitempty"`
	ID          string           `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	Labels      []*MapFieldEntry `protobuf:"bytes,4,rep,name=Labels,proto3" json:"Labels,omitempty"`
	ParentID    []string         `protobuf:"bytes,5,rep,name=ParentID,proto3" json:"ParentID,omitempty"`
	RepoTags    []string         `protobuf:"bytes,6,rep,name=RepoTags,proto3" json:"RepoTags,omitempty"`
	SharedSize  int64            `protobuf:"varint,7,opt,name=SharedSize,proto3" json:"SharedSize,omitempty"`
	Size        int64            `protobuf:"varint,8,opt,name=Size,proto3" json:"Size,omitempty"`
	VirtualSize int64            `protobuf:"varint,9,opt,name=VirtualSize,proto3" json:"VirtualSize,omitempty"`
}

func (x *ImageListEntry) Reset() {
	*x = ImageListEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListEntry) ProtoMessage() {}

func (x *ImageListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListEntry.ProtoReflect.Descriptor instead.
func (*ImageListEntry) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{1}
}

func (x *ImageListEntry) GetContainers() int64 {
	if x != nil {
		return x.Containers
	}
	return 0
}

func (x *ImageListEntry) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImageListEntry) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ImageListEntry) GetLabels() []*MapFieldEntry {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ImageListEntry) GetParentID() []string {
	if x != nil {
		return x.ParentID
	}
	return nil
}

func (x *ImageListEntry) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *ImageListEntry) GetSharedSize() int64 {
	if x != nil {
		return x.SharedSize
	}
	return 0
}

func (x *ImageListEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageListEntry) GetVirtualSize() int64 {
	if x != nil {
		return x.VirtualSize
	}
	return 0
}

type ImageListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ImageListEntry `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ImageListReply) Reset() {
	*x = ImageListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListReply) ProtoMessage() {}

func (x *ImageListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListReply.ProtoReflect.Descriptor instead.
func (*ImageListReply) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{2}
}

func (x *ImageListReply) GetList() []*ImageListEntry {
	if x != nil {
		return x.List
	}
	return nil
}

type ImageHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageID string `protobuf:"bytes,1,opt,name=ImageID,proto3" json:"ImageID,omitempty"`
}

func (x *ImageHistoryRequest) Reset() {
	*x = ImageHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageHistoryRequest) ProtoMessage() {}

func (x *ImageHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageHistoryRequest.ProtoReflect.Descriptor instead.
func (*ImageHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{3}
}

func (x *ImageHistoryRequest) GetImageID() string {
	if x != nil {
		return x.ImageID
	}
	return ""
}

type ImageHistoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ImageHistoryEntry `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ImageHistoryReply) Reset() {
	*x = ImageHistoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageHistoryReply) ProtoMessage() {}

func (x *ImageHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageHistoryReply.ProtoReflect.Descriptor instead.
func (*ImageHistoryReply) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{4}
}

func (x *ImageHistoryReply) GetList() []*ImageHistoryEntry {
	if x != nil {
		return x.List
	}
	return nil
}

type ImageHistoryEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment   string   `protobuf:"bytes,1,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Created   int64    `protobuf:"varint,2,opt,name=Created,proto3" json:"Created,omitempty"`
	CreatedBy string   `protobuf:"bytes,3,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	ID        string   `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	Size      int64    `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Tags      []string `protobuf:"bytes,6,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *ImageHistoryEntry) Reset() {
	*x = ImageHistoryEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageHistoryEntry) ProtoMessage() {}

func (x *ImageHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageHistoryEntry.ProtoReflect.Descriptor instead.
func (*ImageHistoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{5}
}

func (x *ImageHistoryEntry) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ImageHistoryEntry) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImageHistoryEntry) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ImageHistoryEntry) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ImageHistoryEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageHistoryEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ImageSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term         string           `protobuf:"bytes,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Filters      []*MapFieldEntry `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"` // filter
	RegistryAuth string           `protobuf:"bytes,3,opt,name=RegistryAuth,proto3" json:"RegistryAuth,omitempty"`
	Limit        int32            `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *ImageSearchRequest) Reset() {
	*x = ImageSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchRequest) ProtoMessage() {}

func (x *ImageSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchRequest.ProtoReflect.Descriptor instead.
func (*ImageSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{6}
}

func (x *ImageSearchRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *ImageSearchRequest) GetFilters() []*MapFieldEntry {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ImageSearchRequest) GetRegistryAuth() string {
	if x != nil {
		return x.RegistryAuth
	}
	return ""
}

func (x *ImageSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ImageSearchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ImageSearchEntry `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ImageSearchReply) Reset() {
	*x = ImageSearchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageSearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchReply) ProtoMessage() {}

func (x *ImageSearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchReply.ProtoReflect.Descriptor instead.
func (*ImageSearchReply) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{7}
}

func (x *ImageSearchReply) GetList() []*ImageSearchEntry {
	if x != nil {
		return x.List
	}
	return nil
}

type ImageSearchEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StarCount   int32  `protobuf:"varint,1,opt,name=StarCount,proto3" json:"StarCount,omitempty"`
	IsOfficial  bool   `protobuf:"varint,2,opt,name=IsOfficial,proto3" json:"IsOfficial,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	IsAutomated bool   `protobuf:"varint,4,opt,name=IsAutomated,proto3" json:"IsAutomated,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (x *ImageSearchEntry) Reset() {
	*x = ImageSearchEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_images_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageSearchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchEntry) ProtoMessage() {}

func (x *ImageSearchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_images_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchEntry.ProtoReflect.Descriptor instead.
func (*ImageSearchEntry) Descriptor() ([]byte, []int) {
	return file_proto_images_proto_rawDescGZIP(), []int{8}
}

func (x *ImageSearchEntry) GetStarCount() int32 {
	if x != nil {
		return x.StarCount
	}
	return 0
}

func (x *ImageSearchEntry) GetIsOfficial() bool {
	if x != nil {
		return x.IsOfficial
	}
	return false
}

func (x *ImageSearchEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageSearchEntry) GetIsAutomated() bool {
	if x != nil {
		return x.IsAutomated
	}
	return false
}

func (x *ImageSearchEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_images_proto protoreflect.FileDescriptor

var file_proto_images_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a,
	0x10, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x41, 0x6c, 0x6c, 0x12, 0x2e, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x22, 0x96, 0x02, 0x0a, 0x0e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x2c, 0x0a, 0x06, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65,
	0x70, 0x6f, 0x54, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65,
	0x70, 0x6f, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x56, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x3b, 0x0a, 0x0e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x44, 0x22, 0x41, 0x0a, 0x11, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x9d, 0x01,
	0x0a, 0x11, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x42, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x22, 0x92, 0x01,
	0x0a, 0x12, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x2e, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x41, 0x75, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x41, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x3f, 0x0a, 0x10, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0xa8, 0x01, 0x0a, 0x10, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x4f, 0x66, 0x66, 0x69,
	0x63, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x4f, 0x66,
	0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73,
	0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x49, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xd3,
	0x01, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x73, 0x68, 0x61, 0x6e, 0x77, 0x65, 0x6e, 0x2f,
	0x70, 0x6c, 0x75, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_images_proto_rawDescOnce sync.Once
	file_proto_images_proto_rawDescData = file_proto_images_proto_rawDesc
)

func file_proto_images_proto_rawDescGZIP() []byte {
	file_proto_images_proto_rawDescOnce.Do(func() {
		file_proto_images_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_images_proto_rawDescData)
	})
	return file_proto_images_proto_rawDescData
}

var file_proto_images_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_images_proto_goTypes = []interface{}{
	(*ImageListRequest)(nil),    // 0: proto.ImageListRequest
	(*ImageListEntry)(nil),      // 1: proto.ImageListEntry
	(*ImageListReply)(nil),      // 2: proto.ImageListReply
	(*ImageHistoryRequest)(nil), // 3: proto.ImageHistoryRequest
	(*ImageHistoryReply)(nil),   // 4: proto.ImageHistoryReply
	(*ImageHistoryEntry)(nil),   // 5: proto.ImageHistoryEntry
	(*ImageSearchRequest)(nil),  // 6: proto.ImageSearchRequest
	(*ImageSearchReply)(nil),    // 7: proto.ImageSearchReply
	(*ImageSearchEntry)(nil),    // 8: proto.ImageSearchEntry
	(*MapFieldEntry)(nil),       // 9: proto.MapFieldEntry
}
var file_proto_images_proto_depIdxs = []int32{
	9, // 0: proto.ImageListRequest.filters:type_name -> proto.MapFieldEntry
	9, // 1: proto.ImageListEntry.Labels:type_name -> proto.MapFieldEntry
	1, // 2: proto.ImageListReply.list:type_name -> proto.ImageListEntry
	5, // 3: proto.ImageHistoryReply.list:type_name -> proto.ImageHistoryEntry
	9, // 4: proto.ImageSearchRequest.filters:type_name -> proto.MapFieldEntry
	8, // 5: proto.ImageSearchReply.list:type_name -> proto.ImageSearchEntry
	0, // 6: proto.Image.ImageList:input_type -> proto.ImageListRequest
	3, // 7: proto.Image.ImageHistory:input_type -> proto.ImageHistoryRequest
	6, // 8: proto.Image.ImageSearch:input_type -> proto.ImageSearchRequest
	2, // 9: proto.Image.ImageList:output_type -> proto.ImageListReply
	4, // 10: proto.Image.ImageHistory:output_type -> proto.ImageHistoryReply
	7, // 11: proto.Image.ImageSearch:output_type -> proto.ImageSearchReply
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_images_proto_init() }
func file_proto_images_proto_init() {
	if File_proto_images_proto != nil {
		return
	}
	file_proto_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_images_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_images_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageListEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_images_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_images_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_images_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageHistoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_images_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageHistoryEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_images_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_images_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageSearchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_images_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageSearchEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_images_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_images_proto_goTypes,
		DependencyIndexes: file_proto_images_proto_depIdxs,
		MessageInfos:      file_proto_images_proto_msgTypes,
	}.Build()
	File_proto_images_proto = out.File
	file_proto_images_proto_rawDesc = nil
	file_proto_images_proto_goTypes = nil
	file_proto_images_proto_depIdxs = nil
}
